name: Notify Teams on Issue Close

on:
  issues:
    types: [closed]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Send message to Teams
      # Message content is in Markdown format
      # Message content includes a link to the issue
      run: |
        curl -H "Content-Type: application/json" -d "{\"text\": \"Issue closed: [${{ github.event.issue.title }}](${{ github.event.issue.html_url }})\"}" ${{ secrets.TEAMS_WEBHOOK_URL }}
